/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "Acc.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(Acc)

 Acc::Acc(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _Th,
                        RooAbsReal& _Sl) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   Th("Th","Th",this,_Th),
   Sl("Sl","Sl",this,_Sl)
 {
 }


 Acc::Acc(const Acc& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   Th("Th",this,other.Th),
   Sl("Sl",this,other.Sl)
 {
 }



 Double_t Acc::evaluate() const
 {
   double result;
   result = (TMath::Erf(Sl*(x-Th))+1)/2.;
   return result ;
 }
