/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DSCB
#define DSCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class dscb : public RooAbsPdf {
public:
  dscb() {} ; 
  dscb(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _x0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _ANeg,
	      RooAbsReal& _PNeg,
	      RooAbsReal& _APos,
	      RooAbsReal& _PPos);
  dscb(const dscb& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new dscb(*this,newname); }
  inline virtual ~dscb() { }

protected:

  RooRealProxy x ;
  RooRealProxy x0 ;
  RooRealProxy sigma ;
  RooRealProxy ANeg ;
  RooRealProxy PNeg ;
  RooRealProxy APos ;
  RooRealProxy PPos ;
  
  Double_t evaluate() const ;

private:

  ClassDef(dscb,1) // Your description goes here...
};
 
#endif
